---
stages: [hygiene, build, publish]

default:
  image: python:latest
  cache:
    paths: [.cache/pip]
  before_script: [python -V, pip install hatch]

variables:
  EMAIL: threatintel@volexity.com
  HATCH_INDEX_AUTH: $ARTIFACTORY_TOKEN
  HATCH_INDEX_REPO: https://artifactory.research.volexity.com/artifactory/api/pypi/pypi-volexity-services
  HATCH_INDEX_USER: $ARTIFACTORY_USER
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
  PIP_INDEX_URL: https://artifactory.research.volexity.com/artifactory/api/pypi/pypi/simple

lint:
  stage: hygiene
  tags: [docker]
  image: python:3.12-bookworm
  script: [hatch fmt]

type:
  stage: hygiene
  tags: [docker]
  image: python:3.12-bookworm
  script: [hatch run types:check]

deb:
  stage: build
  tags: [docker]
  image: python:3.12-bookworm
  artifacts:
    paths: [./*.deb]
  script:
    - echo "deb https://artifactory.research.volexity.com/artifactory/debian-proxy/
      bookworm main contrib non-free" > /etc/apt/sources.list
    - echo "deb-src https://artifactory.research.volexity.com/artifactory/debian-proxy/
      bookworm main contrib non-free" >> /etc/apt/sources.list
    - echo "deb https://artifactory.research.volexity.com/artifactory/debian-proxy/
      bookworm-updates main contrib non-free" >> /etc/apt/sources.list
    - echo "deb-src https://artifactory.research.volexity.com/artifactory/debian-proxy/
      bookworm-updates main contrib non-free" >> /etc/apt/sources.list
    - echo "deb https://artifactory.research.volexity.com/artifactory/debian-proxy/
      bookworm-backports main" >> /etc/apt/sources.list
    - echo "deb-src https://artifactory.research.volexity.com/artifactory/debian-proxy/
      bookworm-backports main" >> /etc/apt/sources.list
    - echo "deb https://artifactory.research.volexity.com/artifactory/debian-security-proxy/
      bookworm-security main contrib non-free" >> /etc/apt/sources.list
    - echo "deb-src https://artifactory.research.volexity.com/artifactory/debian-security-proxy/
      bookworm-security main contrib non-free" >> /etc/apt/sources.list
    - apt update
    - apt install -y build-essential debhelper-compat devscripts dh-python pybuild-plugin-pyproject
      python3-all python3-hatchling python3-hatch-vcs
    - dch -v `hatch version` --distribution unstable 'See repository...'
    - dpkg-buildpackage
    - mv ../*.deb .

wheel:
  stage: build
  tags: [docker]
  image: python:3.12-bookworm
  artifacts:
    paths: [dist/*]
  script: [hatch build]

artifactory:
  stage: publish
  tags: [docker]
  image: python:3.12-bookworm
  script: [hatch publish]
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+(.\d+)+$/
